[package]
name = "leakdetector"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
walkdir = "2.5.0"
git2 = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.12.5"
tempfile = "3.10.1"